
local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)

cfg.groups = {
  ["superadmin"] = {
    _config = {onspawn = function(player) vRPclient._notify(player,"You are superadmin.") end},
    "player.group.add",
    "player.group.remove",
    "player.givemoney",
    "player.giveitem",
    "admin.god",
    "admin.tptowaypoint",
    "admin.cmd_pos"
  },
  ["admin"] = {
    "admin.tickets",
    "admin.announce",
    "player.list",
    "admin.tptowaypoint",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.unban",
    "player.noclip",
    "player.custom_emote",
    "player.custom_sound",
    "player.display_custom",
    "player.coords",
    "player.tptome",
    "player.tpto",
    "player.tptowaypoint",
    "admin.cmd_pos",    
    "admin.god"
  },
  ["god"] = {
    "admin.god" -- reset survivals/health periodically
  },
  -- the group user is auto added to all logged players
  ["user"] = {
    "player.cmd_mask",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "process.money",
    "police.store_weapons",
    "police.seizable" -- can be seized
  },
  --CORREGEDORIA
  ["[CRD] Comandante Geral"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "player.group.add",
    "player.group.remove",
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "policia.garagem",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Comandante.paycheck",
  } ,  
  --PM 
  ["[PMESP] Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "policia.garagem",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Coronel.paycheck"
  } ,   
  ["[PMESP] Tenete Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "TenenteCoronel.paycheck"
  } ,   
  ["[PMESP] Major"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "policia.garagem",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Major.paycheck"
  } ,  
  ["[PMESP] Capitão"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Capitão.paycheck"
  } ,  
  ["[PMESP] 1º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "policia.garagem",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "1ºTenente.paycheck"
  } ,  
  ["[PMESP] 2º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "policia.garagem",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "2ºTenente.paycheck"
  } ,  
  ["[PMESP] Sub-Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "policia.garagem",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Sub-Tenente.paycheck"
  } ,  
  ["[PMESP] Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "policia.garagem",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Sargento.paycheck"
  } , 
  ["[PMESP] 1º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "policia.garagem",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "1ºSargento.paycheck"
  } ,  
  ["[PMESP] 2º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "policia.garagem",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "2ºSargento.paycheck"
  } ,  
  ["[PMESP] 3º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "policia.garagem",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "3ºSargento.paycheck"
  } ,  
  ["[PMESP] Cabo"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Cabo.paycheck"
  } ,  
  ["[PMESP] Soldado"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "policia.garagem",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Soldado.paycheck"
  } ,  
  -- ROCAM
  ["[ROCAM] Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "policia.garagem",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Coronel.paycheck"
  } ,   
  ["[ROCAM] Tenete Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "TenenteCoronel.paycheck"
  } ,   
  ["[ROCAM] Major"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "policia.garagem",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Major.paycheck"
  } ,  
  ["[ROCAM] Capitão"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "policia.garagem",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Capitão.paycheck"
  } ,  
  ["[ROCAM] 1º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "policia.garagem",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "1ºTenente.paycheck"
  } ,  
  ["[ROCAM] 2º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "2ºTenente.paycheck"
  } ,  
  ["[ROCAM] Sub-Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "3ºTenente.paycheck"
  } ,  
  ["[ROCAM] Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Sargento.paycheck"
  } , 
  ["[ROCAM] 1º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "policia.garagem",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "1ºSargento.paycheck"
  } ,  
  ["[ROCAM] 2º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "2ºSargento.paycheck"
  } ,  
  ["[ROCAM] 3º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "policia.garagem",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "3ºSargento.paycheck"
  } ,  
  ["[ROCAM] Cabo"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "policia.garagem",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Cabo.paycheck"
  } ,  
  ["[ROCAM] Soldado"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Soldado.paycheck"
  } ,
  -- FORÇA TÁTICA
  ["[FT] Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Coronel.paycheck"
  } ,   
  ["[FT] Tenete Coronel"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "policia.garagem",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "TenenteCoronel.paycheck"
  } ,   
  ["[FT] Major"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "policia.garagem",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Major.paycheck"
  } ,  
  ["[FT] Capitão"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "policia.garagem",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Capitão.paycheck"
  } ,  
  ["[FT] 1º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "1ºTenente.paycheck"
  } ,  
  ["[FT] 2º Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "policia.garagem",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "2ºTenente.paycheck"
  } ,  
  ["[FT] Sub-Tenente"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "policia.garagem",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Sub-Tenente.paycheck"
  } ,  
  ["[FT] Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Sargento.paycheck"
  } , 
  ["[FT] 1º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "1ºSargento.paycheck"
  } ,  
  ["[FT] 2º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "policia.garagem",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "2ºSargento.paycheck"
  } ,  
  ["[FT] 3º Sargento"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "policia.garagem",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "3ºSargento.paycheck"
  } ,  
  ["[FT] Cabo"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "policia.garagem",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Cabo.paycheck"
  } ,  
  ["[FT] Soldado"] = {
    _config = { 
      gtype = "job",
      onjoin = function(player) vRPclient._setCop(player,true) end,
      onspawn = function(player) vRPclient._setCop(player,true) end,
      onleave = function(player) vRPclient._setCop(player,false) end
    },
    "police.menu",
    "police.cloakroom",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "policia.garagem",
    "police.seize.weapons",
    "police.seize.items",
    "police.jail",
    "police.fine",
    "police.announce",
    "police.weapons",
    "police.asklc",
    "police.takelc",
    "police.askid",
    "police.cmd_plate",
    "-police.store_weapons",
    "-police.seizable",
    "Soldado.paycheck"
  } ,
  ["[SSP] Samu"] = {
    _config = { gtype = "job" },
    "player.cmd_team",
    "emergency.revive",
    "emergency.shop",
    "emergency.service",
    "samu.medkit",
    "samu.cloakroom",
    "samu.garagem",
    "Samu.paycheck"
  },
  --===================--
    --EMPREGOS LEGAIS
  --===================--
  ["Carteiro"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,"Você é Carteiro.") end
  },
    "player.cmd_mask",
    "player.cmd_team",
    "carteiro.cloakroom",
    "mission.delivery.carteiro",
    "mission.delivery.carta",
    "carteiro.garagem",
	  "carteiro.gopostal",
	  "carteiro.paycheck"
  },
  ["Transportador de Valores"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,"Você é um piloto de carro forte.") end
  },
    "player.cmd_mask",
    "player.cmd_team",
    "valores.cloakroom",
    "valores.garagem",
	  "mission.bankdriver.moneybank",
	  "mission.bankdriver.moneybank2",
	  "bankdriver.vehicle",
	  "bankdriver.paycheck",
	  "bankdriver.money"
  },
  ["Minerador de Diamante"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,"Você é Minerador.") end
  },
    "player.cmd_mask",
    "player.cmd_team",
    "harvest.minerio",
    "process.pedregulho",
    "process.pedralisa",
    "venda.diamantes",
	  "minerador.garagem",
	  "minerador.cloakroom"
  },
  ["Eletricista"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,"Você é Eletricista.") end
  },
    "player.cmd_mask",
    "player.cmd_team",
	  "eletricista.garagem",
	  "eletricista.cloakroom",
	  "mission.repair.satellite_dishes",
	  "mission.repair.wind_turbines",
	  "eletricista.paycheck"
  },
  ["Lenhador"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,"Você é Lenhador.") end
  },
    "player.cmd_mask",
    "player.cmd_team",
    "harvest.lenha",
    "mission.delivery.lenhador",
    "mission.delivery.lenha"
  },
  ["Lixeiro"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,"Você é um lixeiro.") end
  },
    "player.cmd_mask",
    "player.cmd_team",
    "harvest.lixo",
    "mission.delivery.lixeiro",
    "mission.delivery.lixo"
  },
  ["Mecanico"] = {
    _config = { gtype = "job"},
    "player.cmd_mask",
    "player.cmd_team",
    "vehicle.repair",
    "vehicle.replace",
    "repair.service"
  },
  ["Uber"] = {
    _config = { gtype = "job" },
    "player.cmd_mask",
    "player.cmd_team",
    "taxi.service"
  },
  ["Desempregado"] = {
    _config = { gtype = "job" }
  },
  --===================--
    --EMPREGOS ILEGAIS
  --===================--
  ["Ladrão de Carros"] = {
    _config = { gtype = "job" },
    "player.cmd_mask",
    "mission.carjack.vehicle"
},
  ["Traficante de Maconha"] = {
    _config = { gtype = "job" },
    "player.cmd_mask",
    "harvest.weed",
    "process.weed",
    "mission.delivery.weed",
    "mission.delivery.pot"
},
  ["Traficante de Metanfetamina"] = {
    _config = { gtype = "job" },
    "player.cmd_mask",
    "harvest.metanfetamina",
    "process.metanfetamina",
    "mission.delivery.metanfetamina",
    "mission.delivery.pot3"
},  
  ["Traficante de Cocaina"] = {
    _config = { gtype = "job" },
    "player.cmd_mask",
    "process.cocaina",
    "harvest.cocaina",
    "mission.delivery.cocaina",
    "mission.delivery.pot2"
},  
  ["Traficante de Crack"] = {
    _config = { gtype = "job" },
    "player.cmd_mask",
    "process.crack",
    "harvest.crack",
    "mission.delivery.crack",
    "mission.delivery.pot4"
}, 
  ["Traficante de Armas"] = {
    _config = { gtype = "job" },
    "build.gun",
    "mission.delivery.pistol",
    "mission.delivery.shotgun",
    "mission.delivery.smg",
    "player.cmd_mask",
    "mission.gunrunner.shipment"
},
  ["Assassino Profissional"] = {
    _config = { gtype = "job" },
    "hitman.takebounty",
    "-hitman.addbounty",
    "-player.blips",
    "player.cmd_mask",
    "mission.hitman"
},
  ["Hacker"] = {
    _config = { gtype = "job" },
    "-player.blips",
    "player.cmd_mask",
    "hacker.hack"
},
  ["Assaltante"] = {
    _config = { gtype = "job" },
    "-player.blips",
    "player.cmd_mask",
    "mugger.mug"
}
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "superadmin",
    "admin"
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["Empregos"] = {
    _config = {x = -268.363739013672, y = -957.255126953125, z = 31.22313880920410, blipid = 351, blipcolor = 47},
    "Uber",
    "Mecanico",
    "Eletricista",
    "Minerador de Diamante",
    "Transportador de Valores",
    "Carteiro",
    "Lenhador",
    "Lixeiro",
    "Desempregado"
  },
  ["Empregos Ilegais"] = {
    _config = {x = 705.6227417, y = -963.9260864, z = 30.39534569, blipid = 351, blipcolor = 47},
    "Ladrão de Carros",
    "Traficante de Maconha",
    "Traficante de Cocaina",
    "Traficante de Crack",
    "Traficante de Metanfetamina",
    "Hacker",
    "Assaltante"
  }
}

return cfg

